### ISSUE TITLE
Plugin enables/disables itself when anyone starts their chat message with "at"

### ISSUE THREAD

**Issue by gimleey** [NightmareXIV/TextAdvance#16]
The plugin doesn't check for the / (slash) for the /at command so anyone can disable or enable the plugin if their chat message starts with "at". I had one of my party members type "at nine" in party chat and it enabled my textadvance.

**Comment by Eternita-S** [comment]
Hello. Can you replicate it? Or make some sort of video/something?
This should not be possible

**Comment by gimleey** [comment]
Here's [a video.](https://www.youtube.com/watch?v=yAco3UB1838)
I tested it a bit more and it does the exact same thing for other plugins (like /pmb for the market board plugin) so I'll close the issue. It's probably some weird interaction with another plugin, I know PartyIcons scans party chat for people typing m1, r1 and the like in chat to assign them their role but it was still doing it when I disabled it so idk.
