### ISSUE TITLE
Overlay repositioning and scaling

### ISSUE THREAD

**Issue by vaultor** [NightmareXIV/TextAdvance#18]
Hey, would be great if the overlay can be repositioned by mouse, and the text size scalable in options. I play on non-fullscreen, smaller window due to work environment, so the overlay doesn't move together with the game client when I reposition it. Additionally, I would really appreciate if the overlay can be moved to the second monitor.

**Comment by Limiana** [comment]
> so the overlay doesn't move together with the game client when I reposition it
this sounds like a bug actually
