### ISSUE TITLE
TextAdvance Update not available

### ISSUE THREAD

**Issue by rinrinad** [NightmareXIV/TextAdvance#19]
The installer tried to update but failed.

**Comment by doggjoe9** [comment]
latest.zip is not included in the newest release.

**Comment by rinrinad** [comment]
Are you saying that this is not possible from the plugin installer?

**Comment by rinrinad** [comment]
Resolved. Thanks for writing the explanation.

**Comment by Limiana** [comment]
The issue is resolved, was a faulty upload. You should be able to update now!
