### ISSUE TITLE
Does not play some voices?

### ISSUE THREAD

**Issue by Theletha** [NightmareXIV/TextAdvance#24]
Im using elven Labs and sometimes it doesn't play the npc. 
In the new msq Krile and Wuk Lamat were talking and the tts did not work with them for the non voiced scenes.
Same with the "Concerned Researcher" in the dungeon event u go into in the msq and some book readings: https://i.imgur.com/ho98KmY.png

Tried adding them to the npc voices 
Also tried to enable channel settings to all

It works if i remove ungendered option. but gendered works on system ai

**Comment by Limiana** [comment]
Hello!
I think you have opened issue at a wrong plugin?

**Comment by Theletha** [comment]
yes you are right sorry !
