### ISSUE TITLE
Weird navigation behaviour

### ISSUE THREAD

**Issue by AetherCollective** [NightmareXIV/TextAdvance#29]
So this is happening when I try to use TextAdvance to navigate to an NPC for me (with vnavmesh). I have to right click the task and then it will walk me. This didnt used to happen
https://github.com/NightmareXIV/TextAdvance/assets/7028351/badb4e98-baab-424b-b01c-fc7afad4985e

**Comment by Limiana** [comment]
Should be resolved in new version now
