### ISSUE TITLE
"Automatic Reward Pick" crashes game when interacting with some npcs

### ISSUE THREAD

**Issue by Dubsys** [NightmareXIV/TextAdvance#32]
![ffxiv_dx11_2024-07-11_23-52-29](https://github.com/NightmareXIV/TextAdvance/assets/2124370/a94e994c-a1ed-4b0e-8b8d-5d3c0577a3d2)

If you need a quick, easy example it seems like if I have Automatic Reward Pick enabled when handing in this quest Dalamud crashes.

[dalamud_appcrash_20240711_234954_301_19980.log](https://github.com/user-attachments/files/16178475/dalamud_appcrash_20240711_234954_301_19980.log)

**Comment by Limiana** [comment]
Hello! 
Could you please attach the rest of the logs? Specifically, dalamud.log.
There are few people who are crashing and I suspect interference from another plugin

**Comment by Limiana** [comment]
Nevermind, I managed to reproduce this issue

**Comment by Limiana** [comment]
The issue should be resolved now
